### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ShalhevetGamliel** [NaomiO/Polynom#2]
Hi Naomi!
In order to finnish our project we need to:
1.Fix String constructor in Polynom class
2.Create extreme points function 
3.Finish PolynomTest class
4.Import to github
5.Create area calculator function

**Comment by NaomiO** [comment]
Hi Shalhevet my dear!
I finished the extreme points function calculator and now i start working on the area function.
Talk to you soon!

**Comment by ShalhevetGamliel** [comment]
close
